BookForm/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookForm.Models
{
    public class Book
    {
        public int BookId { get; set; }

        [Display(Name ="Book Title")]
        public string BookTitle { get; set; }

        public string Author { get; set; }

        [Display(Name ="ISBN")]
        public string Isbn { get; set; }

        [Display(Name ="Publication Date")]
        [DataType(DataType.Date)]
        public DateTime PublicationDate { get; set; }


    }
}

BookForm/Models/ErrorViewModel.cs
using System;

namespace BookForm.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookForm/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookForm.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookForm.Controllers
{
    public class FormsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(IFormCollection formData)
        {
            //Map form data to Book Object
            Book book = new Book();
            book.BookTitle = formData["book-title"];
            book.Author = formData["author"];
            book.Isbn = formData["isbn"];
            book.PublicationDate = Convert.ToDateTime(formData["publication-date"]);

            //Add to database

            ViewData["Message"] = "Book added successfully";

            return View();
        }
    }
}

BookForm/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BookForm.Models;

namespace BookForm.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookForm/Controllers/ModelBindingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookForm.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookForm.Controllers
{
    public class ModelBindingController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Book book)//mapping is done authomatically
        {
            if (ModelState.IsValid)
            {
                //Add to database

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

    }
}

BookForm/Views/Forms/Index.cshtml
@{
    ViewData["Title"] = "HTML Book Form";
}

    <h1>HTML Book Form</h1>

@if (ViewData["Message"] != null)
{
    <h2 class="alert alert-success">@ViewData["Message"]</h2>
}
else
{
    <form method="post">
        @*<label for="book-title">Title</label>*@
        <input class="form-control form-control-lg" type="text" name="book-title" placeholder="Title" />
        <span>*</span>
        <br />

        @*<label for="author">Author</label>*@
        <input class="form-control form-control-lg" type="text" name="author" placeholder="Author" />
        <span>*</span>
        <br />

        @*<label for="isbn">ISBN</label>*@
        <input class="form-control form-control-lg" type="text" name="isbn" placeholder="ISBN" />
        <span>*</span>
        <br />

        @*<label for="bpublication-date">Publication date</label>*@
        <input class="form-control form-control-lg" type="date" name="publication-date" placeholder="Publication Date"/>
        <span>*</span>
        <br />

        <input type="submit" value="Add book" class="btn btn-dark" />

    </form>
}

BookForm/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookForm/Views/ModelBinding/Index.cshtml
@model Book
@{
    ViewData["Title"] = "Model Binding Book Form";
}

    <h1>Model Binding Book Form</h1>

    <form method="post">
        <input class="form-control form-control-lg" asp-for="BookTitle" name="book-title" placeholder="Title" />
        <span asp-validation-for="BookTitle" class="text-danger"></span>
        <br />

        <input class="form-control form-control-lg" asp-for="Author" name="author" placeholder="Author" />
        <span asp-validation-for="Author" class="text-danger"></span>
        <br />

        <input class="form-control form-control-lg" asp-for="Isbn" name="isbn" placeholder="ISBN" />
        <span asp-validation-for="Isbn" class="text-danger"></span>
        <br />

        <input class="form-control form-control-lg" asp-for="PublicationDate" name="publication-date" placeholder="Publication date" />
        <span asp-validation-for="PublicationDate"class="text-danger"></span>
        <br />


        <input type="submit" value="Add book" class="btn btn-dark" />


    </form>

BookForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookForm</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Forms" asp-action="Index">HTML Book Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ModelBinding" asp-action="Index">Model Binding Book Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Book Form - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>